name: Issue Automation
on: 
    issues:
        types: [opened]
jobs:
    issue-opened:
        runs-on: ubuntu-latest
        steps:
            - name: New Issue Opened
              run: |
                echo "Issue Number: ${{ github.event.issue.number }}"
                echo "Reported by: ${{ github.event.issue.user.name }}"
                echo "Assigned to: ${{ github.event.issue.assignee.name }}"
                echo "Body: ${{ github.event.issue.body }}"
                echo "Issue State: ${{ github.event.issue.body }}"
                
